CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TYPE user_role AS ENUM ('SuperAdmin', 'Admin', 'SubAdmin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE app_users (
        id uuid NOT NULL,
        role user_role NOT NULL,
        status text NOT NULL,
        parent_id uuid,
        email text NOT NULL,
        password_hash text NOT NULL,
        display_name text NOT NULL,
        credit_balance numeric NOT NULL,
        credit_limit numeric NOT NULL,
        is_blocked boolean NOT NULL,
        status_reason text,
        approved_by uuid,
        approved_at timestamp with time zone,
        token_version integer NOT NULL,
        last_login_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_app_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        actor_id uuid,
        action text NOT NULL,
        target_type text,
        target_id text,
        metadata jsonb,
        allowed boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_log" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE blocked_identities (
        id uuid NOT NULL,
        identity_type text NOT NULL,
        identity_hash text NOT NULL,
        reason text,
        flagged_by uuid,
        flagged_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone,
        CONSTRAINT "PK_blocked_identities" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE callback_relays (
        id uuid NOT NULL,
        order_id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        target_url text NOT NULL,
        payload jsonb NOT NULL,
        status text NOT NULL,
        attempt_count integer NOT NULL,
        last_attempt_at timestamp with time zone,
        next_attempt_at timestamp with time zone NOT NULL,
        last_response_code integer,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_callback_relays" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE ledger_entries (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        wallet_id uuid NOT NULL,
        direction text NOT NULL,
        amount numeric NOT NULL,
        ref_type text NOT NULL,
        ref_id uuid NOT NULL,
        balance_after numeric NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ledger_entries" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE orders (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        seller_id uuid,
        merchant_order_ref text NOT NULL,
        amount numeric NOT NULL,
        currency text NOT NULL,
        status text NOT NULL,
        psp_code text NOT NULL,
        psp_order_id text,
        psp_payment_id text,
        payer_vpa_masked text,
        customer_ref text,
        device_fingerprint text,
        ip_address text,
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        completed_at timestamp with time zone,
        customer_name text,
        customer_email text,
        customer_phone text,
        metadata jsonb,
        routing_rule_id uuid,
        payment_provider_id uuid,
        failure_reason text,
        CONSTRAINT "PK_orders" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE payment_providers (
        id uuid NOT NULL,
        owner_user_id uuid NOT NULL,
        tenant_id uuid,
        provider_code text NOT NULL,
        display_name text NOT NULL,
        account_label text NOT NULL,
        merchant_account_ref text,
        key_id text,
        key_secret_enc bytea,
        webhook_secret_enc bytea,
        is_active boolean NOT NULL,
        is_test_mode boolean NOT NULL,
        health_status text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_payment_providers" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE refunds (
        id uuid NOT NULL,
        order_id uuid NOT NULL,
        requested_by uuid,
        amount numeric NOT NULL,
        reason text,
        psp_refund_id text,
        status text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        completed_at timestamp with time zone,
        CONSTRAINT "PK_refunds" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE routing_rules (
        id uuid NOT NULL,
        owner_user_id uuid NOT NULL,
        tenant_id uuid,
        payment_provider_id uuid NOT NULL,
        min_amount numeric NOT NULL,
        max_amount numeric,
        priority integer NOT NULL,
        is_enabled boolean NOT NULL,
        fallback_provider_id uuid,
        payment_method text,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_routing_rules" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE seller_transfers (
        id uuid NOT NULL,
        order_id uuid NOT NULL,
        seller_id uuid NOT NULL,
        psp_transfer_id text,
        seller_amount numeric NOT NULL,
        platform_commission numeric NOT NULL,
        status text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        settled_at timestamp with time zone,
        CONSTRAINT "PK_seller_transfers" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE sellers (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        onboarded_by uuid NOT NULL,
        seller_code text NOT NULL,
        business_name text NOT NULL,
        contact_phone text NOT NULL,
        contact_email text,
        upi_collection_app text,
        psp_code text NOT NULL,
        psp_linked_account_id text,
        commission_percent numeric NOT NULL,
        status text NOT NULL,
        status_reason text,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_sellers" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE tenants (
        id uuid NOT NULL,
        sub_admin_id uuid NOT NULL,
        merchant_code text NOT NULL,
        display_name text NOT NULL,
        vertical text NOT NULL,
        callback_url text NOT NULL,
        commission_percent numeric NOT NULL,
        api_key text NOT NULL,
        api_secret_hash text NOT NULL,
        callback_secret text NOT NULL,
        status text NOT NULL,
        is_active boolean NOT NULL,
        status_reason text,
        approved_by uuid,
        approved_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tenants" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE user_permissions (
        id uuid NOT NULL,
        user_id uuid NOT NULL,
        permission_code text NOT NULL,
        tenant_id uuid,
        granted boolean NOT NULL,
        CONSTRAINT "PK_user_permissions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE user_tenant_access (
        user_id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        CONSTRAINT "PK_user_tenant_access" PRIMARY KEY (user_id, tenant_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE wallets (
        id uuid NOT NULL,
        tenant_id uuid NOT NULL,
        balance numeric NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_wallets" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE TABLE webhook_events (
        id uuid NOT NULL,
        psp_code text NOT NULL,
        psp_event_id text NOT NULL,
        payload jsonb NOT NULL,
        signature_valid boolean NOT NULL,
        psp_order_id text,
        psp_payment_id text,
        outcome text NOT NULL,
        payer_vpa_masked text,
        processing_started_at timestamp with time zone,
        processed_at timestamp with time zone,
        order_id uuid,
        received_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_webhook_events" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_app_users_email" ON app_users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE INDEX "IX_app_users_parent_id_role_status" ON app_users (parent_id, role, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_blocked_identities_identity_type_identity_hash" ON blocked_identities (identity_type, identity_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_orders_tenant_id_merchant_order_ref" ON orders (tenant_id, merchant_order_ref);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tenants_api_key" ON tenants (api_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tenants_merchant_code" ON tenants (merchant_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE INDEX "IX_tenants_sub_admin_id_status" ON tenants (sub_admin_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_permissions_user_id_permission_code_tenant_id" ON user_permissions (user_id, permission_code, tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_webhook_events_psp_code_psp_event_id" ON webhook_events (psp_code, psp_event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261006065944_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261006065944_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

