import { useEffect, useState } from 'react';
import { getSummary, getWebsites } from '../api/platform';
import { useOrderLifecycle } from '../hooks/useOrderLifecycle';
import type { PlatformSummary, Website } from '../types';
export function DashboardHome(){
 const[data,setData]=useState<PlatformSummary|null>(null),[websites,setWebsites]=useState<Website[]>([]),[tenantId,setTenantId]=useState(''),[range,setRange]=useState('today'),[error,setError]=useState('');const{events}=useOrderLifecycle();
 function params(){const end=new Date(),start=new Date();if(range==='7d')start.setDate(end.getDate()-7);else if(range==='30d')start.setDate(end.getDate()-30);else start.setHours(0,0,0,0);return{tenantId:tenantId||undefined,from:start.toISOString(),to:end.toISOString()};}
 async function load(){try{setError('');setData(await getSummary(params()));}catch(e:any){setError(e?.response?.data?.error??'Unable to load platform metrics.');}}
 useEffect(()=>{void load();void getWebsites().then(setWebsites).catch(()=>{});},[tenantId,range]);
 if(error)return <div className="notice">{error}</div>;if(!data)return <div className="empty">Loading control center…</div>;const rate=data.successful+data.failed?data.successful/(data.successful+data.failed)*100:0;const activity=data.recentPayments.length?data.recentPayments:events.map(e=>({id:e.orderId,tenantId:e.tenantId,merchantOrderRef:e.orderId,amount:e.amount,currency:e.currency,status:e.status,psp:'live',customer:null,createdAt:e.at}));
 return <><div className="hero"><div><div className="eyebrow">EXECUTIVE OVERVIEW</div><h2>Payment control center</h2><p>Real-time portfolio visibility across merchants, routing and PSP operations.</p></div><div className="toolbar"><select className="select" value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">All merchant websites</option>{websites.map(w=><option key={w.id} value={w.id}>{w.displayName}</option>)}</select><select className="select" value={range} onChange={e=>setRange(e.target.value)}><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option></select></div></div>
 <div className="grid kpi-grid"><K label="Successful collection" value={`₹${data.collection.toLocaleString('en-IN',{maximumFractionDigits:0})}`} meta={`${data.successful.toLocaleString()} successful payments`}/><K label="Success rate" value={`${rate.toFixed(1)}%`} meta={`${data.failed.toLocaleString()} failed attempts`}/><K label="Pending" value={data.pending.toLocaleString()} meta="Awaiting terminal outcome"/><K label="Merchant websites" value={data.activeWebsites.toString()} meta={`${data.pendingWebsites} pending approval`}/><K label="PSP / routes" value={`${data.providerAccounts} / ${data.activeRoutes}`} meta="Provider accounts / active routes"/></div>
 <div className="grid two-col"><section className="card section"><div className="section-head"><h3>Collection health</h3><span className="muted">{rate.toFixed(1)}% success</span></div><div className="health-bar"><div className="health-success" style={{width:`${Math.min(100,rate)}%`}}/><div className="health-failed" style={{width:`${Math.min(100,Math.max(0,100-rate))}%`}}/></div><div className="health-grid"><div className="health-stat success"><span className="health-dot"/><div><b>{data.successful.toLocaleString()}</b><small>Successful</small></div></div><div className="health-stat failed"><span className="health-dot"/><div><b>{data.failed.toLocaleString()}</b><small>Failed</small></div></div><div className="health-stat pending"><span className="health-dot"/><div><b>{data.pending.toLocaleString()}</b><small>Pending</small></div></div></div></section><section className="card section"><div className="section-head"><h3>Live payment activity</h3><span className="muted">{events.length} live events</span></div><div className="activity">{activity.slice(0,10).map(p=><div className="activity-row" key={p.id}><span className="activity-dot"/><div className="activity-copy"><b>{p.merchantOrderRef}</b><span>{p.psp} · {new Date(p.createdAt).toLocaleString()}</span></div><strong>₹{Number(p.amount).toLocaleString('en-IN')}</strong></div>)}</div>{!activity.length&&<div className="empty">No payment activity for this period.</div>}</section></div>
 <div className="grid three-col"><section className="card section"><span className="eyebrow">MERCHANTS</span><h3 style={{marginTop:8}}>Active websites</h3><strong className="big-number">{data.activeWebsites}</strong><p className="muted">Scoped by the signed-in operator's permissions.</p></section><section className="card section"><span className="eyebrow">GOVERNANCE</span><h3 style={{marginTop:8}}>Team structure</h3><div className="metric-line"><span>Admins</span><b>{data.admins}</b></div><div className="metric-line"><span>SubAdmins</span><b>{data.subAdmins}</b></div></section><section className="card section"><span className="eyebrow">ROUTING</span><h3 style={{marginTop:8}}>Active routes</h3><strong className="big-number">{data.activeRoutes}</strong><p className="muted">Smart-routing rules currently enabled.</p></section></div></>;
}
function K({label,value,meta}:{label:string;value:string;meta:string}){return <div className="card kpi"><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="kpi-meta">{meta}</div></div>}
