import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { redFlag } from '../api/admin';
import { apiClient } from '../api/client';
import type { RedFlagRequest } from '../types';

interface Blocked { id:string; identityType:string; identityHash:string; reason?:string|null; flaggedAt:string; expiresAt?:string|null; }
export function FraudPage(){
  const [form,setForm]=useState<RedFlagRequest>({identityType:'upi',rawIdentityValue:'',reason:'',temporaryHours:undefined}); const [result,setResult]=useState(''); const [error,setError]=useState(''); const [rows,setRows]=useState<Blocked[]>([]);
  async function load(){try{const {data}=await apiClient.get<Blocked[]>('/api/platform/risk/blocked');setRows(data);}catch(e:any){setError(e?.response?.data?.error??'Unable to load risk controls.');}}
  useEffect(()=>{void load();},[]);
  async function submit(e:FormEvent){e.preventDefault();try{setError('');await redFlag(form);setResult('Identity flagged and hashed before storage.');setForm({identityType:'upi',rawIdentityValue:'',reason:'',temporaryHours:undefined});await load();}catch(e:any){setError(e?.response?.data?.error??'Could not flag this identity.');}}
  return <><div className="hero"><div><h2>Risk control</h2><p>Platform-wide identity blocking with hashed values and expiry support.</p></div></div>{error&&<div className="notice">{error}</div>}{result&&<div className="notice">{result}</div>}<div className="grid two-col"><div className="card section"><h3>Red-flag an identity</h3><form onSubmit={submit}><F l="Identity type"><select className="select" value={form.identityType} onChange={e=>setForm({...form,identityType:e.target.value as RedFlagRequest['identityType']})}><option value="device">Device fingerprint</option><option value="ip">IP address</option><option value="phone">Phone number</option><option value="upi">UPI handle</option><option value="name">Name</option></select></F><F l="Value"><input className="input" required value={form.rawIdentityValue} onChange={e=>setForm({...form,rawIdentityValue:e.target.value})}/></F><F l="Reason"><input className="input" required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></F><F l="Temporary block (hours)"><input className="input" type="number" min="1" value={form.temporaryHours??''} onChange={e=>setForm({...form,temporaryHours:e.target.value?Number(e.target.value):undefined})}/></F><button className="btn" type="submit">Flag identity</button></form></div><div className="card section"><div className="section-head"><h3>Current blocked identities</h3><button className="btn secondary" onClick={()=>void load()}>Refresh</button></div><table className="table"><thead><tr><th>Type</th><th>Reason</th><th>Flagged</th><th>Expires</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.identityType}</td><td>{r.reason??'—'}</td><td>{new Date(r.flaggedAt).toLocaleString()}</td><td>{r.expiresAt?new Date(r.expiresAt).toLocaleString():'Permanent'}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No blocked identities.</div>}</div></div></>;
}
function F({l,children}:{l:string;children:ReactNode}){return <div className="field" style={{marginBottom:11}}><label>{l}</label>{children}</div>}
