import { useEffect, useMemo, useState } from 'react';
import { getPayment, getPayments, getWebsites, refundPayment } from '../api/platform';
import { apiClient } from '../api/client';
import type { Payment, Website } from '../types';

const iso=(v:string)=>v?new Date(v).toISOString():undefined;
export function PaymentsPage(){
  const [rows,setRows]=useState<Payment[]>([]),[websites,setWebsites]=useState<Website[]>([]),[selected,setSelected]=useState<Payment|null>(null);
  const [status,setStatus]=useState(''),[tenantId,setTenantId]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[q,setQ]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function load(){try{setLoading(true);setError('');const params:Record<string,unknown>={};if(status)params.status=status;if(tenantId)params.tenantId=tenantId;if(from)params.from=iso(from);if(to)params.to=iso(to);setRows(await getPayments(params));}catch(e:any){setError(e?.response?.data?.error??'Unable to load payments.');}finally{setLoading(false);}}
  useEffect(()=>{void getWebsites().then(setWebsites).catch(()=>{});void load();},[]);
  const filtered=useMemo(()=>rows.filter(x=>(`${x.merchantOrderRef} ${x.psp} ${x.customer??''} ${x.pspOrderId??''}`).toLowerCase().includes(q.toLowerCase())),[rows,q]);
  async function openPayment(id:string){try{setSelected(await getPayment(id));}catch(e:any){setError(e?.response?.data?.error??'Unable to load payment details.');}}
  async function exportCsv(){try{const params:Record<string,unknown>={};if(status)params.status=status;if(tenantId)params.tenantId=tenantId;if(from)params.from=iso(from);if(to)params.to=iso(to);const r=await apiClient.get('/api/platform/reports/payments.csv',{params,responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=`payorch-payments-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}catch(e:any){setError(e?.message??'Export failed.');}}
  async function refund(){if(!selected)return;const amount=Number(window.prompt(`Refund amount (max ₹${Number(selected.amount).toLocaleString('en-IN')}):`,String(selected.amount)));if(!Number.isFinite(amount)||amount<=0)return;try{await refundPayment(selected.id,amount,window.prompt('Reason:')??'');await openPayment(selected.id);await load();}catch(e:any){setError(e?.response?.data?.error??'Refund failed.');}}
  return <><div className="hero"><div><div className="eyebrow">OPERATIONS / PAYMENTS</div><h2>Payment operations</h2><p>Search, audit and act on every collection attempt across your merchant portfolio.</p></div><button className="btn" onClick={()=>void exportCsv()}>Export CSV</button></div>{error&&<div className="notice">{error}</div>}
  <div className="card section"><div className="toolbar"><input className="input grow" placeholder="Search order, customer or PSP reference…" value={q} onChange={e=>setQ(e.target.value)}/><select className="select" value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">All websites</option>{websites.map(w=><option key={w.id} value={w.id}>{w.displayName} · {w.merchantCode}</option>)}</select><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="Succeeded">Succeeded</option><option value="Failed">Failed</option><option value="IntentLaunched">Pending</option><option value="Expired">Expired</option></select></div><div className="toolbar"><label className="date-field">From<input className="input" type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="date-field">To<input className="input" type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn" onClick={()=>void load()}>{loading?'Loading…':'Apply filters'}</button><button className="btn secondary" onClick={()=>{setStatus('');setTenantId('');setFrom('');setTo('');setQ('');void load();}}>Reset</button><span className="muted">{filtered.length} visible · server filters applied</span></div>
  <table className="table"><thead><tr><th>Merchant reference</th><th>Website</th><th>Amount</th><th>PSP</th><th>Status</th><th>Created</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} onClick={()=>void openPayment(p.id)} className="click-row"><td className="mono">{p.merchantOrderRef}</td><td>{websites.find(w=>w.id===p.tenantId)?.displayName??p.tenantId.slice(0,10)+'…'}</td><td>₹{Number(p.amount).toLocaleString('en-IN')}</td><td><span className="tag">{p.psp}</span></td><td><Status s={p.status}/></td><td>{new Date(p.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No payments match the current filters.</div>}</div>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="section-head"><div><div className="eyebrow">PAYMENT DETAIL</div><h2>{selected.merchantOrderRef}</h2></div><div className="modal-actions"><button className="btn secondary" onClick={()=>setSelected(null)}>Close</button>{selected.status==='Succeeded'&&<button className="btn danger" onClick={()=>void refund()}>Refund</button>}</div></div><div className="detail-grid"><Row l="Payment ID" v={selected.id}/><Row l="Amount" v={`₹${Number(selected.amount).toLocaleString('en-IN')} ${selected.currency}`}/><Row l="Status" v={selected.status}/><Row l="PSP" v={selected.psp}/><Row l="PSP order" v={selected.pspOrderId??'—'}/><Row l="PSP payment" v={selected.pspPaymentId??'—'}/><Row l="Customer" v={selected.customer??'—'}/><Row l="Created" v={new Date(selected.createdAt).toLocaleString()}/><Row l="Completed" v={selected.completedAt?new Date(selected.completedAt).toLocaleString():'—'}/><Row l="Failure reason" v={selected.failureReason??'—'}/></div></div></div>}</>;
}
function Status({s}:{s:string}){return <span className={`status ${s==='Succeeded'?'ok':s==='Failed'?'bad':'wait'}`}>{s}</span>}
function Row({l,v}:{l:string;v:string}){return <div className="detail-row"><span>{l}</span><b className={l.includes('ID')||l.startsWith('PSP')?'mono':''}>{v}</b></div>}
