import { useEffect, useState, type ReactNode } from 'react';
import { changeProviderStatus, checkProviderHealth, createProvider, getProviders, getWebsites } from '../api/platform';
import type { Provider, Website } from '../types';

export function ProvidersPage(){
  const [rows,setRows]=useState<Provider[]>([]); const [sites,setSites]=useState<Website[]>([]); const [open,setOpen]=useState(false); const [error,setError]=useState('');
  const [f,setF]=useState({providerCode:'razorpay',displayName:'Razorpay',accountLabel:'Production account',merchantAccountRef:'',keyId:'',tenantId:'',isActive:true,isTestMode:true});
  async function load(){try{setError('');const [p,s]=await Promise.all([getProviders(),getWebsites()]);setRows(p);setSites(s);}catch(e:any){setError(e?.response?.data?.error??'Unable to load payment providers.');}}
  useEffect(()=>{void load();},[]);
  async function save(){try{await createProvider({...f,tenantId:f.tenantId||null});setOpen(false);await load();}catch(e:any){setError(e?.response?.data?.error??'Unable to create provider.');}}
  async function toggle(p:Provider){try{await changeProviderStatus(p.id,!p.isActive);await load();}catch(e:any){setError(e?.response?.data?.error??'Unable to change provider status.');}}
  async function health(p:Provider){try{await checkProviderHealth(p.id);await load();}catch(e:any){setError(e?.response?.data?.error??'Provider health check failed.');}}
  return <><div className="hero"><div><h2>PSP accounts</h2><p>Connect provider accounts once, then route money with policy instead of code.</p></div><button className="btn" onClick={()=>setOpen(true)}>+ Add provider</button></div>{error&&<div className="notice">{error}</div>}<div className="grid" style={{gridTemplateColumns:'repeat(3,minmax(0,1fr))'}}>{rows.map(p=><div className="card section" key={p.id}><div className="section-head"><h3>{p.displayName}</h3><span className={p.isActive?'status ok':'status bad'}>{p.isActive?'Connected':'Disabled'}</span></div><div className="small">{p.accountLabel}</div><div className="metric-line"><span>Provider</span><b>{p.providerCode}</b></div><div className="metric-line"><span>Mode</span><b>{p.isTestMode?'Test':'Live'}</b></div><div className="metric-line"><span>Health</span><b>{p.healthStatus}</b></div><div className="metric-line"><span>Website</span><b>{sites.find(s=>s.id===p.tenantId)?.displayName??'Platform default'}</b></div><div style={{display:'flex',gap:6}}><button className="btn secondary" onClick={()=>void health(p)}>Test</button><button className="btn secondary" onClick={()=>void toggle(p)}>{p.isActive?'Disable':'Enable'}</button></div></div>)}{!rows.length&&<div className="empty">No provider accounts yet.</div>}</div>{open&&<div className="modal-backdrop"><div className="modal"><h2>Add payment provider</h2><div className="form-grid"><F l="Provider"><select className="select" value={f.providerCode} onChange={e=>setF({...f,providerCode:e.target.value,displayName:e.target.value==='razorpay'?'Razorpay':e.target.value})}><option value="razorpay">Razorpay</option><option value="cashfree">Cashfree</option><option value="phonepe_pg">PhonePe PG</option><option value="paytm_pg">Paytm PG</option></select></F><F l="Account label"><input className="input" value={f.accountLabel} onChange={e=>setF({...f,accountLabel:e.target.value})}/></F><F l="Merchant account ref"><input className="input" value={f.merchantAccountRef} onChange={e=>setF({...f,merchantAccountRef:e.target.value})}/></F><F l="Key ID"><input className="input" value={f.keyId} onChange={e=>setF({...f,keyId:e.target.value})}/></F><F l="Website"><select className="select" value={f.tenantId} onChange={e=>setF({...f,tenantId:e.target.value})}><option value="">Platform default</option>{sites.map(s=><option key={s.id} value={s.id}>{s.displayName}</option>)}</select></F><F l="Mode"><select className="select" value={String(f.isTestMode)} onChange={e=>setF({...f,isTestMode:e.target.value==='true'})}><option value="true">Test</option><option value="false">Live</option></select></F></div><div className="notice">PSP secrets are not accepted by the browser. Store production secrets in the deployment secret manager and configure the adapter.</div><div className="modal-actions"><button className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn" onClick={()=>void save()}>Save account</button></div></div></div>}</>;
}
function F({l,children}:{l:string;children:ReactNode}){return <div className="field"><label>{l}</label>{children}</div>}
