import { useEffect, useState } from 'react';
import { getAuditLogs, getWebsites } from '../api/platform';
import { apiClient } from '../api/client';
import type { AuditLog, Website } from '../types';
export function ReportsPage(){
 const [logs,setLogs]=useState<AuditLog[]>([]),[websites,setWebsites]=useState<Website[]>([]),[tenantId,setTenantId]=useState(''),[action,setAction]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[error,setError]=useState('');
 async function load(){try{setError('');const rows=await getAuditLogs(500);setLogs(rows.filter(x=>(!action||x.action.toLowerCase().includes(action.toLowerCase()))&&(!from||new Date(x.createdAt)>=new Date(from))&&(!to||new Date(x.createdAt)<=new Date(to))));}catch(e:any){setError(e?.response?.data?.error??'Unable to load audit activity.');}}
 useEffect(()=>{void load();void getWebsites().then(setWebsites).catch(()=>{});},[]);
 async function exportPayments(){const params:Record<string,unknown>={};if(tenantId)params.tenantId=tenantId;if(from)params.from=new Date(from).toISOString();if(to)params.to=new Date(to).toISOString();const r=await apiClient.get('/api/platform/reports/payments.csv',{params,responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='payorch-payment-report.csv';a.click();URL.revokeObjectURL(url);}
 return <><div className="hero"><div><div className="eyebrow">GOVERNANCE / REPORTING</div><h2>Reports & audit</h2><p>Merchant-wise reporting, date-range exports and a privileged control-plane audit trail.</p></div><button className="btn" onClick={()=>void exportPayments()}>Export payment report</button></div>{error&&<div className="notice">{error}</div>}
 <div className="card section"><div className="section-head"><div><h3>Report filters</h3><span className="muted">Use the same filters for recurring reconciliation reviews.</span></div></div><div className="toolbar"><select className="select" value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">All websites</option>{websites.map(w=><option key={w.id} value={w.id}>{w.displayName} · {w.merchantCode}</option>)}</select><input className="input" placeholder="Audit action contains…" value={action} onChange={e=>setAction(e.target.value)}/><label className="date-field">From<input className="input" type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="date-field">To<input className="input" type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn" onClick={()=>void load()}>Apply</button><button className="btn secondary" onClick={()=>{setTenantId('');setAction('');setFrom('');setTo('');void load();}}>Reset</button></div></div>
 <div className="grid three-col"><Report title="Payment reconciliation" value="CSV" text="Collection records with merchant reference, website, amount, PSP, status and timestamps."/><Report title="Merchant audit" value={String(logs.length)} text="Privileged actions visible within the signed-in user's hierarchy."/><Report title="Security trail" value="Immutable" text="Login, lifecycle, provider, routing, refund, export and risk-control actions are recorded."/></div>
 <div className="card section" style={{marginTop:16}}><div className="section-head"><div><h3>Audit trail</h3><span className="muted">Newest first · {logs.length} records</span></div><button className="btn secondary" onClick={()=>void load()}>Refresh</button></div><table className="table"><thead><tr><th>Timestamp</th><th>Action</th><th>Target</th><th>Result</th><th>Actor</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{new Date(l.createdAt).toLocaleString()}</td><td><b>{l.action}</b></td><td>{l.targetType??'—'} {l.targetId?<span className="mono">· {l.targetId.slice(0,12)}…</span>:''}</td><td><span className={`status ${l.allowed?'ok':'bad'}`}>{l.allowed?'Allowed':'Denied'}</span></td><td className="mono">{l.actorId?.slice(0,12)??'system'}</td></tr>)}</tbody></table>{!logs.length&&<div className="empty">No audit events match the current filters.</div>}</div></>;
}
function Report({title,value,text}:{title:string;value:string;text:string}){return <div className="card section report-card"><span className="eyebrow">REPORT</span><h3>{title}</h3><strong>{value}</strong><p className="muted">{text}</p></div>}
