import { useEffect, useState, type ReactNode } from 'react';
import { changeSellerStatus, exportSellersCsv, listSellers, onboardSeller } from '../api/admin';
import { getWebsites } from '../api/platform';
import { useAuth } from '../context/AuthContext';
import type { SellerFull, SellerSummary, Website } from '../types';

const isFull=(s:SellerSummary|SellerFull):s is SellerFull=>'businessName' in s;
export function SellersPage(){
  const {user}=useAuth(); const canManage=user?.role==='SuperAdmin'||user?.role==='Admin';
  const [sites,setSites]=useState<Website[]>([]),[tenantId,setTenantId]=useState(''),[sellers,setSellers]=useState<(SellerSummary|SellerFull)[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false);
  const [form,setForm]=useState({businessName:'',contactPhone:'',contactEmail:'',commissionPercent:5});
  async function loadSites(){try{const data=await getWebsites();setSites(data);if(!tenantId&&data.length)setTenantId(data[0].id);}catch(e:any){setError(e?.response?.data?.error??'Unable to load websites.');}}
  async function loadSellers(id=tenantId){if(!id)return;try{setError('');setSellers(await listSellers(id));}catch(e:any){setError(e?.response?.data?.error??'Unable to load sellers.');}}
  useEffect(()=>{void loadSites();},[]);
  useEffect(()=>{if(tenantId)void loadSellers(tenantId);},[tenantId]);
  async function save(){try{await onboardSeller(tenantId,{...form,contactEmail:form.contactEmail.trim()});setOpen(false);setForm({businessName:'',contactPhone:'',contactEmail:'',commissionPercent:5});await loadSellers();}catch(e:any){setError(e?.response?.data?.error??'Unable to onboard seller.');}}
  async function status(s:SellerFull|SellerSummary,action:string){const reason=window.prompt(`Reason for ${action} (optional):`)??'';try{await changeSellerStatus(tenantId,s.id,action,reason);await loadSellers();}catch(e:any){setError(e?.response?.data?.error??`Unable to ${action} seller.`);}}
  async function exportCsv(){try{const result=await exportSellersCsv(tenantId);const blob=new Blob([result.data]);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='payorch-sellers.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(a.href);}catch(e:any){setError(e?.response?.data?.error??'Export blocked for your role.');}}
  return <><div className="hero"><div><h2>Sellers</h2><p>Marketplace merchant onboarding and PSP linked-account lifecycle.</p></div>{canManage&&<button className="btn" disabled={!tenantId} onClick={()=>setOpen(true)}>+ Onboard seller</button>}</div>{error&&<div className="notice">{error}</div>}<div className="card section"><div className="toolbar"><select className="select grow" value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">Select website</option>{sites.map(s=><option key={s.id} value={s.id}>{s.displayName} · {s.merchantCode}</option>)}</select><button className="btn secondary" disabled={!tenantId} onClick={()=>void loadSellers()}>Refresh</button>{canManage&&<button className="btn secondary" disabled={!tenantId} onClick={()=>void exportCsv()}>Export CSV</button>}</div><table className="table"><thead><tr><th>{canManage?'Business name':'Merchant'}</th><th>Code</th><th>Status</th><th>Commission</th>{canManage&&<th>Linked account</th>} {canManage&&<th>Actions</th>}</tr></thead><tbody>{sellers.map(s=><tr key={s.id}><td>{isFull(s)?s.businessName:s.label}</td><td className="mono">{isFull(s)?s.sellerCode:'—'}</td><td><span className={`status ${s.status==='Active'?'ok':s.status==='Rejected'||s.status==='Suspended'?'bad':'wait'}`}>{s.status}</span></td><td>{s.commissionPercent}%</td>{canManage&&<td className="mono">{isFull(s)?s.pspLinkedAccountId??'—':'—'}</td>}{canManage&&<td><SellerActions status={s.status} onAction={a=>void status(s,a)}/></td>}</tr>)}</tbody></table>{!sellers.length&&<div className="empty">No sellers for this website.</div>}</div>{open&&<div className="modal-backdrop"><div className="modal"><h2>Onboard seller</h2><div className="form-grid"><F l="Business name"><input className="input" value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})}/></F><F l="Contact phone"><input className="input" value={form.contactPhone} onChange={e=>setForm({...form,contactPhone:e.target.value})}/></F><F l="Contact email"><input className="input" type="email" value={form.contactEmail} onChange={e=>setForm({...form,contactEmail:e.target.value})}/></F><F l="Commission %"><input className="input" type="number" min="0" max="100" value={form.commissionPercent} onChange={e=>setForm({...form,commissionPercent:Number(e.target.value)})}/></F></div><div className="notice">The seller is created locally and submitted to the configured PSP adapter for linked-account onboarding.</div><div className="modal-actions"><button className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn" onClick={()=>void save()}>Submit seller</button></div></div></div>}</>;
}
function SellerActions({status,onAction}:{status:string;onAction:(a:string)=>void}){const list=status==='Active'?['suspend']:status==='Suspended'||status==='Rejected'?['activate']:status==='PendingReview'||status==='SubmittedToPsp'?['reject']:[];return <div style={{display:'flex',gap:5}}>{list.map(a=><button key={a} className={`btn ${a==='reject'||a==='suspend'?'danger':'secondary'}`} onClick={()=>onAction(a)}>{a}</button>)}</div>}
function F({l,children}:{l:string;children:ReactNode}){return <div className="field"><label>{l}</label>{children}</div>}
